### ISSUE TITLE
Audio Frequency

### ISSUE THREAD

**Issue by FilipeOS** [CasperPas/flutter-sound-stream#10]
Hi there,

How it would be possible to make sound recording only listening to frequencies of 2.35 Hz to 2.51 Hz?

For example record/stream only that frequencies

Thank you!

**Comment by FilipeOS** [comment]
@CasperPas Do you have a theory on this please?

Basically hear heart beat

**Comment by CasperPas** [comment]
I think we can analyze raw audio data and filter it ourselves. Like equalizers or noise cancelling techniques

**Comment by FilipeOS** [comment]
@CasperPas would you be able to do this as a paid job for me?

Or provide me more information because I'm lost

**Comment by CasperPas** [comment]
I'm sorry I cannot do another job during this time (or in the near future). This plug-in is just what I do in my free time (what I'm lacking now)

To do this, you (or some other guy) need to know about DSP (Digital Signal Processing) with some filters like Low-pass or High-pass. As I suggested, try to look for something like equalizer or noise cancellation implementations.

**Comment by CasperPas** [comment]
And because this is not really an issue, I'd like to close it now.
