### ISSUE TITLE
Recorder streaming to HTTP endpoint

### ISSUE THREAD

**Issue by dweberlj** [CasperPas/flutter-sound-stream#17]
Hello,

I am using [dio ](https://pub.dev/packages/dio)HTTP client for dart and want to POST the microphone audio stream.  I tried the following code but it did not work.  I call openMic on a UI button press.  Any suggestions?

```
  Future<void> openMic() async {
    _recorderStatus = _recorder.status.listen((status) async {
      print("Recorder status: " + status.toString());
      if (status == SoundStreamStatus.Initialized) {
        _recorder.start();
        _isRecording = true;
      }
      if (status == SoundStreamStatus.Playing) {
        print("Stream is playing");
        try {
          Dio dio = new Dio();
          Response response = await dio.post(
              serverBase + "/audioStreamer",
              data: _recorder.audioStream,
              options: Options(
                headers: {
                },
              )
          );
        } catch (e) {
          closeMic();
          print("POST error: " + e.response.statusCode.toString());
        }
      }
    });
```

Error output:

```
I/flutter ( 4480): Recorder status: SoundStreamStatus.Initialized
I/flutter ( 4480): Recorder status: SoundStreamStatus.Playing
I/flutter ( 4480): Stream is playing
E/flutter ( 4480): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: NoSuchMethodError: The getter 'statusCode' was called on null.
E/flutter ( 4480): Receiver: null
E/flutter ( 4480): Tried calling: statusCode
```

**Comment by AyadRocketfy** [comment]
Hello @dweberlj,

If you want to stream you should use sockets for that.
There is an example using dart for the server part: 
- Server side: https://github.com/CasperPas/flutter-sound-stream/blob/master/example/server/server.dart
- Client side: https://github.com/CasperPas/flutter-sound-stream/blob/master/example/lib/main-talky.dart

This example will stream like a walky talkie.
I have tested it and it works.

The error you are getting it's because it's not a dio exception. You can check this way:

`if (e is DioError) {
        String error = 'Status code: ${e.response.statusCode}';

        if (e.response.statusCode == 401) {
          error = '${e.response.data['message']}';
        }

        print(e.response.statusCode);
        print(e.response.data);

        print(error);
      }

      print('$e');`

**Comment by dweberlj** [comment]
Thanks @AyadRocketfy, we'll check out the client dart example and connect it to our nodejs server.  Should be pretty straight forward.

Regards,
Dean

**Comment by AyadRocketfy** [comment]
You welcome @dweberlj :)

**Comment by alysonrode** [comment]
Can i get a similar result using sockets and not websockets? Im tryng to communicate two smartphones and transmit audio that between them, but it hasen't work as i expected

**Comment by 2math** [comment]
> Can i get a similar result using sockets and not websockets? Im tryng to communicate two smartphones and transmit audio that between them, but it hasen't work as i expected

Have you tried to use 1st device as a hotspot and connect from the second device?

**Comment by alysonrode** [comment]
> Have you tried to use 1st device as a hotspot and connect from the second device?

Hey Math, thanks for replying! :)

My problem was solved using the "add" parameter in socket and preparing the socket as broadcast stream.
