### ISSUE TITLE
iOS implementation throwing mDNS errors and not connecting to microphone stream

### ISSUE THREAD

**Issue by mdeloge** [CasperPas/flutter-sound-stream#18]
Hi,

The sound_stream package works as expected on Android but on iOS 14+ (and possibly other versions as well, but only validated on those versions) the microphone stream seemingly is never accessed. In the logs I can see an mDNS related error being thrown:

```
2020-09-30 07:50:58.127826+0200 Runner[15040:6082532] Metal API Validation Enabled
2020-09-30 07:50:58.706114+0200 Runner[15040:6082799] flutter: Observatory listening on http://127.0.0.1:65353/xeoyak9eH7w=/
2020-09-30 07:51:00.456957+0200 Runner[15040:6082532] [VERBOSE-2:FlutterObservatoryPublisher.mm(115)] Failed to register observatory port with mDNS.
```

I made sure the microphone permission is set correctly as I get a `Permission.granted` using the `permission_handler` package.
Currently I have a plan B solution in place using the on device speech to text contained in the `speech_to_text` package. 

Since the documentation mentions both iOS and Android to be working, I was kind of expecting this to work out-of-the-box, so hopefully a solution can be found in the near future.

Thanks in advance for looking into this issue.

**Comment by CasperPas** [comment]
Did you solved the issue? I found this stackoverflow link: https://stackoverflow.com/questions/65168918/flutter-ios-14-0-build-error-failed-to-register-observatory-port-with-mdns

I believe this plugin is not the root cause.
