### ISSUE TITLE
Audio Stream

### ISSUE THREAD

**Issue by FilipeOS** [CasperPas/flutter-sound-stream#3]
Hi there,

How can I be able to stream audio without saving it? like an amplifier without saving it

Thank you

**Comment by CasperPas** [comment]
It's possible to implement it on platform side (iOS, Android), but currently, I just stop the audio engine to make it do 1 task at a time, for less complication. It should be implemented in future versions.
BTW, any PR is welcome 😄

**Comment by FilipeOS** [comment]
I'll try to help you with PR if possible.

I was able to start and stop the recording (not streaming yet unfortunately), how can I play only the last chunk and save it alone in a file .mp3 for example?

**Comment by CasperPas** [comment]
I have an example of writing audio data to WAV file in this PR. Hope that helps.
https://github.com/CasperPas/flutter-sound-stream/pull/5

**Comment by FilipeOS** [comment]
I need to change pubspec to this right?

```
sound_stream:
    git:
      url: git://github.com/CasperPas/flutter-sound-stream.git
```

I'm confused on how I should use it. I was testing this way, saves but it's like corrupted..

```
Future<void> _saveFile() async {
    var now = new DateTime.now();
    var formatter = new DateFormat('yyyy-MM-dd_HH:mm');
    String timerName = formatter.format(now);

    Fluttertoast.showToast(toastLength: Toast.LENGTH_SHORT, msg: "File saved");

    await _localPath.then((local) async {
      _recordedFile = File("$local/Sound$timerName.aac");

      for (var chunk in _micChunks) {
        _recordedFile.writeAsBytesSync(chunk, flush: true);
      }

      setState(() {
        _isSaved = true;
      });
    });
  }
```

**Comment by CasperPas** [comment]
you can clone it to a local folder and checkout the branch `feature/cross_platform_stream`
and then follow this to use it locally:
https://flutter.dev/docs/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages
```
dependencies:
  plugin1:
    path: ../plugin1/
```

**Comment by CasperPas** [comment]
BTW, in your code, you just write the header. You need to save it to a buffer, or write directly to a temporary file (as in my example). And then when you're finished recording, write the header and then copy (append) the temp file's content into your actual WAV file (HEADER then DATA)

**Comment by CasperPas** [comment]
or, if you can wait, I'll try to change the platform side to allow it to play and record simultaneously tomorrow

**Comment by FilipeOS** [comment]
Ok I wait, thank you!

I'm basically trying to have 3 buttons,
1 is the main one to listen/streaming immediately (this is controlling the recording too, the only difference is that will play on speaker or whatever immediately).
2 is for play the record file (_micChunk)
3 is to save to a .wav file

Platform side do you mean to release it to public? so I don't need to copy code?

**Comment by FilipeOS** [comment]
I tried this (since I don't use websockets and its all local):

```
Future<void> _saveFile() async {
    int totalAudioLen = _micChunks.length;
    int longSampleRate = 44100;
    int channels = 16000;
    int byteRate = 16 * 16000 ~/ 8;
    final totalDataLen = totalAudioLen + 36;

    var now = new DateTime.now();
    var formatter = new DateFormat('yyyy-MM-dd_HH:mm');
    String timerName = formatter.format(now);

    Fluttertoast.showToast(toastLength: Toast.LENGTH_SHORT, msg: "File saved");

    await _localPath.then((local) async {
      _recordedFile = File("$local/BabyShell_$timerName.wav");
      File tmp = File("$local/BabyShell_$timerName.wav.tmp");

      _recordedFile.openWrite();
      tmp.openWrite();
      int dataSize = 0;

      Uint8List header = Uint8List.fromList([
        ...utf8.encode('RIFF'),
        (totalDataLen & 0xff),
        ((totalDataLen >> 8) & 0xff),
        ((totalDataLen >> 16) & 0xff),
        ((totalDataLen >> 24) & 0xff),
        ...utf8.encode('WAVEfmt '),
        16, // 4 bytes: size of 'fmt ' chunk
        0,
        0,
        0,
        1, // format = 1
        0,
        channels,
        0,
        (longSampleRate & 0xff),
        ((longSampleRate >> 8) & 0xff),
        ((longSampleRate >> 16) & 0xff),
        ((longSampleRate >> 24) & 0xff),
        (byteRate & 0xff),
        ((byteRate >> 8) & 0xff),
        ((byteRate >> 16) & 0xff),
        ((byteRate >> 24) & 0xff),
        (1), // block align
        0,
        16, //_RECORDER_BPP
        0,
        ...utf8.encode('data'),
        (totalAudioLen & 0xff),
        ((totalAudioLen >> 8) & 0xff),
        ((totalAudioLen >> 16) & 0xff),
        ((totalAudioLen >> 24) & 0xff),
      ]);
      _recordedFile.writeAsBytesSync(header);

      _recordedFile.writeAsBytesSync(tmp.readAsBytesSync(),
          flush: true, mode: FileMode.append);
      tmp.deleteSync();
      tmp = null;

      final Uint8List buff = _micChunks;
      dataSize += buff.lengthInBytes;
      print(dataSize);
      tmp?.writeAsBytesSync(buff, flush: true, mode: FileMode.append);

      setState(() {
        _isSaved = true;
      });
    });
  }
```

But the `final Uint8List buff = _micChunks;` say `value type List<Uint8List> can't be assigned to a type Uint8List`

**Comment by CasperPas** [comment]
@FilipeOS 
> But the `final Uint8List buff = _micChunks;` say `value type List<Uint8List> can't be assigned to a type Uint8List`

of course you cannot assign `List<Uint8List>` to a `Uint8List` variable. `_micChunks` is a **List**, just do a loop through it and put each item into the file.

BTW, I've just updated my code to `master`, it can record and play at the same time now.

**Comment by FilipeOS** [comment]
Thank you! What is the code to record and play at same time?

I tried to use this to save but did not work.
```
final Uint8List buff;
for (var chunk in _micChunks) {
           _recordedFile.writeAsBytesSync(buff, flush: true, mode: FileMode.append);
      }
```

**Comment by CasperPas** [comment]
have you tried to run my example? does it works?

**Comment by FilipeOS** [comment]
Hi there,

Yes but don't work.
I want to record and play at same time, like an amplifier.

On my code I have 2 buttons, 1st when you click should stream and record at same time because on my 2nd button I'm just playing (like listen again).

I have this:
```
RecorderStream _recorder = RecorderStream();
  PlayerStream _player = PlayerStream();

  List<Uint8List> _micChunks = [];
  bool _isRecording = false;
  bool _isPlaying = false;

  StreamSubscription _recorderStatus;
  StreamSubscription _playerStatus;
  StreamSubscription _audioStream;
```

```
Future<void> _initRecorder() async {
    _recorderStatus = _recorder.status.listen((status) {
      if (mounted)
        setState(() {
          _isRecording = status == SoundStreamStatus.Playing;
        });
    });

    _audioStream = _recorder.audioStream.listen((data) {
      _player.writeChunk(data);
      _micChunks.add(data);
    });

    _playerStatus = _player.status.listen((status) {
      if (mounted)
        setState(() {
          _isPlaying = status == SoundStreamStatus.Playing;
        });
    });

    await Future.wait([
      _recorder.initialize(),
      _player.initialize(),
    ]);
  }
```

```
            GestureDetector(
              onTap: () async {
                  if (_isRecording) {
                    _recorder.stop();
                  } else {
                    _micChunks.clear(); //this is to allow me to only have 1 record saved, I know that this can be improved but I just don't know how.
                    _recorder.start(); //This is the recorder, works fine but should stream at same time
                  }
                setState(() {});
              },
```

According the example, you .writeChunk to player but I'm not starting the player on the record button, I tried but don't work.
I tried `await _player.start();` after `_recorder.start();` but was not successful

thank you for all your help.

**Comment by CasperPas** [comment]
In my Example:
https://github.com/CasperPas/flutter-sound-stream/blob/7948a871d0dd6e408f702b9f18bb146032e56266/example/lib/main.dart#L52

This will put recorded data directly to player if it's in `Playing` state, if not, it will save audio data in to `_micChunks` buffer.

https://github.com/CasperPas/flutter-sound-stream/blob/7948a871d0dd6e408f702b9f18bb146032e56266/example/lib/main.dart#L73

`_play` func first starts the player if it's not, then push all saved audio "chunks" (if there's any) into player's buffer.

I tried my example multiple times and it's still working as intended.
- Have you started the player yet?
- Is your phone volume high enough?
- Is your phone on _silent_ mode?

**Comment by FilipeOS** [comment]
Hi there,

_isRecording should (in my case) play instantly, saving and playing.

_isPlaying I only use for the "player", when user wants to ear over and over again

You understand now? Or I'm confusing something?

**Comment by FilipeOS** [comment]
@CasperPas When I record+play at same time the volume is always at max and comes with a huge ear pain noise on speaker, impossible to listen at all, any advise?

**Comment by tmekfouldji** [comment]
> @CasperPas When I record+play at same time the volume is always at max and comes with a huge ear pain noise on speaker, impossible to listen at all, any advise?

I have the same issue, Have you found a solution ?

**Comment by FilipeOS** [comment]
> > @CasperPas When I record+play at same time the volume is always at max and comes with a huge ear pain noise on speaker, impossible to listen at all, any advise?
> 
> I have the same issue, Have you found a solution ?

This is due sound on earpiece and not phone speaker, a user found a solution but it seems it was deprecated and still are no news about it on this plugin..
