### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by tmxdyf** [CasperPas/flutter-sound-stream#35]
java.lang.IllegalArgumentException
E/AndroidRuntime( 9968): 	at java.nio.ByteBuffer.allocate(ByteBuffer.java:280)
E/AndroidRuntime( 9968): 	at vn.casperpas.sound_stream.SoundStreamPlugin$createRecordListener$1.onPeriodicNotification(SoundStreamPlugin.kt:390)
E/AndroidRuntime( 9968): 	at android.media.AudioRecord$NativeEventHandler.handleMessage(AudioRecord.java:1709)
E/AndroidRuntime( 9968): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 9968): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 9968): 	at android.app.ActivityThread.main(ActivityThread.java:6819)
E/AndroidRuntime( 9968): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9968): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:497)
E/AndroidRuntime( 9968): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:912)

**Comment by avvari-da** [comment]
Am having the same issue. This seems to happen for a few devices only.

**Comment by ignertic** [comment]
I ran into this and I realized the crash occurs when you call **PlayerStream.start()** before you have written/pushed any chunks to the stream

**Comment by CasperPas** [comment]
It's merged. I'll fix some other issues then deploy new version.
