### ISSUE TITLE
Not able to play audio in iOS Device

### ISSUE THREAD

**Issue by mukeshlokare** [CasperPas/flutter-sound-stream#4]
Hello there,

I am not able to play the sound in ios. 

can we work together to solve this?

**Comment by CasperPas** [comment]
Sure, could you tell me the steps to reproduce the issue?

**Comment by mukeshlokare** [comment]
Whenever I try to play live sound stream across the device using socket io.

**Comment by mukeshlokare** [comment]
Can we work together with my team to resolve this? please

**Comment by CasperPas** [comment]
If you're streaming data from Android to iOS or vice versa, it's not working (yet). Please check this PR (checkout the branch to test it out).
https://github.com/CasperPas/flutter-sound-stream/pull/5
