### ISSUE TITLE
No control over volume level

### ISSUE THREAD

**Issue by YusufEmad04** [CasperPas/flutter-sound-stream#41]
This library works perfectly well but there is an issue that I cannot control audio volume level. It is always set on the highest volume even if the phone is muted.

**Comment by mowgliho** [comment]
I had this issue as well (on samsung phones in particular). I worked around it by using the volume_watcher package (as the volume from this package is correct, and is responsive to volume buttons) - and just scaled my inputs to the sound stream based on these values.

**Comment by YusufEmad04** [comment]
Actually yesterday I was able to solve this issue on android by deleting i think line 318 which was the method setFlags() inside the library file SoundStreamPlugin.kt

But does this issue also happen on ios?
Because I am considering building an app with sound stream on android and ios

**Comment by mowgliho** [comment]
on iOS, the issues I have are:
1) Sound playback does not work at all on bluetooth headphones (e.g. AirPods)
2) Volume is quiet on regular speakers

sometimes it crashes if you plug/unplug headphones

I think that it's using the wrong stream or something, but I dunno.

**Comment by artyomkonyaev** [comment]
@mowgliho Hi, have you been able to solve the issues that you mentioned?
1. Sound playback does not work at all on bluetooth headphones (e.g. AirPods)
2. Volume is quiet on regular speakers

**Comment by CasperPas** [comment]
Please refer to this issue: https://github.com/CasperPas/flutter-sound-stream/issues/38

The plugin should work with headsets now. It now works fine on my iPhone and Pixel phone. But for Samsung devices, I haven’t got any good solution yet for the volume and output devices.
