### ISSUE TITLE
Error while adding the package. Execution failed for task ':sound_stream:compileDebugKotlin'.

### ISSUE THREAD

**Issue by satymshrma** [CasperPas/flutter-sound-stream#47]
Hello.

An error popped up while I was trying to add the package. Some method somewhere was not overriding anything.

![image](https://user-images.githubusercontent.com/44706382/166453129-8bba7ce0-0e0d-4fd1-b7a6-2cd3593074e8.png)

I've also found the solution though.

You have to go to the file linked and remove the '?' symbol from line 182. After intArray and after string>

Build again, and it should run fine now.

**Comment by refonseca** [comment]
Thanks @satymshrma this workaround works for me.

**Comment by mowgliho** [comment]
workaround worked for me too!

**Comment by AlexanderHorielko** [comment]
This works for me if anyone need it https://github.com/AlexanderHorielko/flutter-sound-stream

sound_stream:
    git:
      url: https://github.com/AlexanderHorielko/flutter-sound-stream.git
      ref: android-fix

**Comment by avdhootu27** [comment]
@satymshrma I tried your solution it worked for me to build the app, but it throws an exception when I use the package to record an audio stream. Same exception occurs in case of @AlexanderHorielko's solution.
The exception is as follows


> E/SoundStreamPlugin(30859): Unexpected exception
E/SoundStreamPlugin(30859): java.lang.NullPointerException
E/SoundStreamPlugin(30859): 	at vn.casperpas.sound_stream.SoundStreamPlugin.startRecording(SoundStreamPlugin.kt:267)
E/SoundStreamPlugin(30859): 	at vn.casperpas.sound_stream.SoundStreamPlugin.onMethodCall(SoundStreamPlugin.kt:108)
E/SoundStreamPlugin(30859): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/SoundStreamPlugin(30859): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/SoundStreamPlugin(30859): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/SoundStreamPlugin(30859): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/SoundStreamPlugin(30859): 	at android.os.Handler.handleCallback(Handler.java:883)
E/SoundStreamPlugin(30859): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/SoundStreamPlugin(30859): 	at android.os.Looper.loop(Looper.java:224)
E/SoundStreamPlugin(30859): 	at android.app.ActivityThread.main(ActivityThread.java:7590)
E/SoundStreamPlugin(30859): 	at java.lang.reflect.Method.invoke(Native Method)
E/SoundStreamPlugin(30859): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/SoundStreamPlugin(30859): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (30859): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(Unknown, Unexpected exception, null, null)
E/flutter (30859): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
E/flutter (30859): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
E/flutter (30859): <asynchronous suspension>
E/flutter (30859): #2      _HomeScreenState.startAudioRecording (package:helpmelisten/Home/home_screen.dart:50:5)
E/flutter (30859): <asynchronous suspension>
E/flutter (30859):

Anyone have any idea how to solve it ?

**Comment by Jonny5-5** [comment]
I had to remove both of the '?' symbols.  One in line 182 and one in line 183.  
Here is a similar issue:
https://github.com/am15h/tflite_flutter_plugin/issues/195

**Comment by CasperPas** [comment]
this should be fixed with the latest version.
