### ISSUE TITLE
android studio throw error by just adding dependency 

### ISSUE THREAD

**Issue by shubham7400** [CasperPas/flutter-sound-stream#51]
C:\Users\pc\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\sound_stream-0.3.0\android\src\main\kotlin\vn\casperpas\sound_stream\SoundStreamPlugin.kt: (45, 8): Class 'SoundStreamPlugin' is not abstract and does not implement abstract member public abstract fun onRequestPermissionsResult(p0: Int, p1: Array<(out) String!>, p2: IntArray): Boolean defined in io.flutter.plugin.common.PluginRegistry.RequestPermissionsResultListener
e: C:\Users\pc\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\sound_stream-0.3.0\android\src\main\kotlin\vn\casperpas\sound_stream\SoundStreamPlugin.kt: (182, 5): 'onRequestPermissionsResult' overrides nothing

**Comment by alexanderrichter99** [comment]
did you manage to solve it? I have the same problem..

**Comment by jeanlucthumm** [comment]
This is the same issue as https://github.com/CasperPas/flutter-sound-stream/issues/54

If you make the changes described there, it works.

**Comment by CasperPas** [comment]
This was fixed and deployed. Thanks!
