### ISSUE TITLE
Orange microphone bubble remains on iOS even after RecorderStream disposed.

### ISSUE THREAD

**Issue by hmirza1** [CasperPas/flutter-sound-stream#62]
![Image](https://github.com/CasperPas/flutter-sound-stream/assets/61479270/2fc8ab1a-e3b0-483f-aad9-3b5710f6022a)

This is resolved once the app is killed. Any ideas?

**Comment by rstewart22** [comment]
Probably this https://github.com/CasperPas/flutter-sound-stream/pull/49

**Comment by SujeethGowda** [comment]
If you add stopEngine() code inside the stopRecording in the native implementation of the sound_stream ios code you can resolve the issue.

private func stopRecording(_ result: @escaping FlutterResult) {
        stopEngine()
        mAudioEngine.inputNode.removeTap(onBus: mRecordBus)
        sendRecorderStatus(SoundStreamStatus.Stopped)
        result(true)
    }
