### ISSUE TITLE
Could not resolve io.ktor:ktor-client-core:2.3.8.

### ISSUE THREAD

**Issue by shubham7400** [CasperPas/flutter-sound-stream#66]
I am creating a compose Multiplatform project with android, IOS and web. when I am adding ktor dependency I am getting this error.

`commonMain.dependencies {
 
            implementation(libs.ktor.client.core)
          

        }`

`Could not resolve all dependencies for configuration ':composeApp:wasmJsCompileClasspath'.
> Could not resolve io.ktor:ktor-client-core:2.3.8.
  Required by:
      project :composeApp
   > No matching variant of io.ktor:ktor-client-core:2.3.8 was found. The consumer was configured to find a library for use during 'kotlin-api', preferably optimized for non-jvm, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm', attribute 'org.jetbrains.kotlin.wasm.target' with value 'js' but:
       - Variant 'iosArm64ApiElements-published' capability io.ktor:ktor-client-core:2.3.8 declares a library for use during 'kotlin-api':
           - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'wasm'
           - Other compatible attributes:
               - Doesn't say anything about its target Java environment (preferred optimized for non-jvm)
               - Doesn't say anything about org.jetbrains.kotlin.wasm.target (required 'js')`
               
               
               do ktor support kotlin/wasm or not?

**Comment by CasperPas** [comment]
Not sure what happened. Could it be more helpful if you ask in ktor issues?
