### ISSUE TITLE
Playback has some slight crackle in the background, and i/o is only through device mic/speakers

### ISSUE THREAD

**Issue by chi-tea-72** [CasperPas/flutter-sound-stream#7]
Hello,

This is a really great plugin, I've been looking for this exact functionality for a while now, so thank you for building this!

I have two issues to note as I was experimenting with the included example:
1) During playback I can hear a crackle every few frames (I think) in the background. It doesn't really cut into the actual playback, but it's certainly noticeable.

2) As far as I can tell I'm unable to use normal headphones (with a mic) to record and playback. All i/o appears to go through the device only

Notes:
- I'm using a real Android device running Android version 10

Thanks again for this plugin!

**Comment by chi-tea-72** [comment]
Also wanted to note that the device volume controls didn't have any impact on the playback volume level.

**Comment by CasperPas** [comment]
Thank you for your report. I'll take a look into this.

**Comment by chi-tea-72** [comment]
Hello,
Just wanted to check on this issue. I'm mainly curious about a fix for being able to record via a wired headset or over bluetooth instead of only via the actual device microphone.

Thanks

**Comment by FilipeOS** [comment]
I can confirm this, playback is crackling all the time and it's ignoring my media volume, always on max volume

**Comment by FilipeOS** [comment]
@CasperPas updates on this?

**Comment by CasperPas** [comment]
I made some fixes for other devices, but I still haven’t had any good solution for Samsung devices (recently got a Samsung phone).
